title: Samuel Sturrock 
description: Computer Science Student | Software Developer
site_title: 'Samuel Sturrock'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SamuelSturrock
email: SamuelSturrock@outlook.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: G-DM699HY5NF
